# Generated by Django 6.0.7 on 2026-09-15 10:03

import django.core.validators
import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentMetadata",
            fields=[
                (
                    "experiment_id",
                    models.CharField(max_length=28, primary_key=True, serialize=False),
                ),
                ("user_email", models.EmailField(max_length=250)),
                (
                    "experiment_description",
                    models.CharField(blank=True, max_length=250),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("RUNNING", "RUNNING"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="QUEUED",
                        max_length=9,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "docked_structures_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DockingParameters",
            fields=[
                (
                    "docking_parameters_entry_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "docking_type",
                    models.CharField(
                        choices=[
                            ("BLIND", "Blind Docking"),
                            ("SITE_SPECIFIC", "Site Specific Docking"),
                        ],
                        default="BLIND",
                        max_length=13,
                    ),
                ),
                (
                    "box_center_x",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "box_center_y",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "box_center_z",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "box_size_x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "box_size_y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "box_size_z",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "experiment_ref",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.experimentmetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigandMolecules",
            fields=[
                (
                    "ligand_entry_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "provided_ligand",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "docking_status",
                    models.CharField(
                        blank=True,
                        choices=[("DOCKED", "DOCKED"), ("FAILED", "FAILED")],
                        max_length=6,
                    ),
                ),
                (
                    "experiment_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.experimentmetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DockingResults",
            fields=[
                (
                    "result_record_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "pose_num",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "binding_affinity",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("rmsd_lb", models.DecimalField(decimal_places=5, max_digits=7)),
                ("rmsd_ub", models.DecimalField(decimal_places=5, max_digits=7)),
                (
                    "experiment_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.experimentmetadata",
                    ),
                ),
                (
                    "ligand_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.ligandmolecules",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceptorMolecule",
            fields=[
                (
                    "receptor_entry_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "provided_receptor",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            website.models.validate_pdb_input,
                            website.models.check_pdb_exists,
                        ],
                    ),
                ),
                ("receptor_structure_components", models.JSONField(default=dict)),
                ("selected_receptor_components", models.JSONField(default=dict)),
                (
                    "experiment_ref",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.experimentmetadata",
                    ),
                ),
            ],
        ),
    ]
